storage:    'C:\\Program Files\\HuarayTech\\MV Viewer\\Development\\Samples\\Python\\uvss_last\\Storage'
database:   'C:\\Program Files\\HuarayTech\\MV Viewer\\Development\\Samples\\Python\\uvss_last\\Storage\\Database'
platecam:   'C:\\temp\\'
chassiscam: 'C:\\Program Files\\HuarayTech\\MV Viewer\\Development\\Samples\\Python\\uvss_last\\ChassisCam'